sw5e-foundry/sw5e

sw5e.css
=> RazznfrazznCSSzn

module/item/entity.js
Still had reference to cantrip instead of atwill
=> Fix for At Will scaling

.gitignore, less/actors.less, less/apps.less, less/variables.less, package-lock.json, sw5e.css
Effectively resets our css file to match what DnD has, but with our colors and fonts. Some small changes needed to get fonts to fit. Will not be 100% identical to what we had, but overall matches decently.
I'm going to make a separate branch to test out a rework of the character sheet to better match the SW5e `a e s t h e t i c`
=> basic setup to use less for css compilation

less/update/components/actor-global.less, less/update/components/actor-themes.less, less/update/components/foundry-app-window-themes.less, package-lock.json, sw5e-dark.css, sw5e-global.css, sw5e-light.css
A few tweaks to the character sheet and modals
=> small style updates

module/actor/entity.js, module/apps/trait-selector.js
This is a patch to the DND5E system pulled from the DND5E gitlab site
=> Fix deprecated use of isPC

less/update/components/actor-global.less, sw5e-global.css
Fixed images flowing out of sheet header
=> fixed character sheet image overflow

module/actor/sheets/newSheet/character.js
Added code to the new character.js file to support the fighting styles section.
=> Added section for fighting styles to new character sheet

less/update/sw5e-global.less, module/actor/sheets/newSheet/character.js, module/actor/sheets/newSheet/npc.js, module/item/entity.js, sw5e-global.css, sw5e.css, templates/actors/newActor/character-sheet.html, templates/actors/newActor/parts/swalt-traits.html
There are still some outstanding issues, namely the fact that the sheet is stretched the width of the window, but it now opens and looks similar to the previous base.
Also ran the less compile, but I think we may need to carefully review it for regressions as I feel there were more outputted changes than expected.
=> Enable display of character sheet

.github/workflows/main.yml, gulpfile.js, package-lock.json, package.json, sw5e-global.css
Uses GitHub actions to automatically build the less files with gulp whenever a PR is opened on or code is pushed to develop or master.
=> Auto build less

module/actor/sheets/newSheet/base.js
What's that? You don't like when the sheet jumps back to the top when you edit something? Psshhhhh
(Closes #98)
=> Fix for sheet losing scroll position

less/update/_variables-light.less, less/update/components/sidebar-themes.less, less/update/components/sidebar.less, sw5e-light.css, templates/actors/newActor/parts/swalt-traits.html
Fixes gear inoperability on character sheet traits and improvies legibility of HUD and chat input/textarea.
=> CSS/LESS and New Char Sheet Hotfixes

module/migration.js
=> Hotfix o 1.2.4 version

less/update/components/sidebar-themes.less, sw5e-dark.css, sw5e-global.css, sw5e-light.css
^ Updates text and background colors for the sidebar Chat text area to make text more legible.
=> Updates to CSS/LESS (Chat text area)

less/update/_variables-light.less, less/update/_variables.less, less/update/components/forms-themes.less, less/update/sw5e-dark.less, sw5e-dark.css, sw5e-global.css, sw5e-light.css
@unrealkakeman89 If you don't want this to go into master, let me know and I will retarget it.
=> Hotfixes for some minor css issues

module/migration.js, sw5e.js, system.json
=> Power point upgrades are finally done

module/characterImporter.js
Prevents the duplication of the character importer button. This also fixes the actor search bar.
Closes #161.
=>  Fixes button duplication

module/actor/sheets/newSheet/base.js
Don't increase power cell quantity, just create a new one.
=> Always create a new power cell

module/actor/entity.js, module/actor/old_entity.js
I think this is good now.  I ran through it quick.  I was able to edit max tech/force points/powers known with DAE.  It also calculated powers known again.
=> Split powercasting

module/actor/entity.js, system.json
Fixed NPC power DCs resolving to NaN
Fixed player power points not adding Mods
=> Various powercasting bugs

module/item/entity.js
I noticed standard ammunition is consumed when an attack roll finishes, including when the attack button is clicked multiple times. However, blasters configured to consume another item's charges consume the charges only once when the item is rolled into chat.
This adds some logic to the ammo consumption code to make charges ammo be consumed like regular ammo
=> Consume ammo charges on attack

module/actor/sheets/newSheet/base.js, module/actor/sheets/oldSheets/base.js, module/apps/property-attribution.js, module/config.js, module/item/sheet.js, module/migration.js, module/pixi/ability-template.js, sw5e.js, system.json, template.json, templates/items/equipment.html
Update Core to 1.4.2 and internal Version to 1.4.2.R1-A8
=> Update Core to 1.4.2

lang/en.json, module/actor/entity.js, module/item/entity.js, module/settings.js
[Rule](https://sw5e.com/rules/variantRules/Simplified%20Forcecasting)
=> Simplified Forcecasting variant rule

module/active-effect.js, module/actor/entity.js, module/actor/sheets/newSheet/base.js, module/actor/sheets/newSheet/npc.js, module/actor/sheets/newSheet/starship.js, module/actor/sheets/oldSheets/base.js, module/actor/sheets/oldSheets/npc.js, module/apps/ability-use-dialog.js, module/apps/select-items-prompt.js, module/apps/short-rest.js, module/item/entity.js, module/migration.js, sw5e.js, system.json
Update Core to 1.5.6 and internal Version to 1.5.6.R1-B1 since R1-B1 was never pushed
=> Update Core to 1.5.6

module/actor/sheets/newSheet/character.js, module/apps/ability-use-dialog.js, module/item/entity.js, module/item/sheet.js, module/migration.js
Mostly name swaps to current API
This should fix a delete bug on v9 and prevent errors in the future if things are deprecated again.
=> Update Entity and Owned Items to current

module/actor/entity.js
- deployment into token document starship
- actor tracking of some deployments
=> 2 bugfixes

module/actor/sheets/newSheet/character.js
fix deprecated call in v9 Foundry
=> Update character.js for item delete call in v9 Foundry

module/display-cr.js, sw5e.js
Displays the CR of NPCs in the actor directory. Resolves Feature Request #180
=> Added NPC CR to actor directory

module/display-cr.js, sw5e.js
Updated to add CR into the Monsters compendium when opened.
=> Added CR on compendium

module/actor/entity.js
Update to allow weapons to be equipped / unequipped
=> Updated for weapons

module/actor/sheets/newSheet/starship.js
Automatically adds deployment features into the Crew tab.
=> Automate Crew Deployment Features

module/config.js, module/item/sheet.js, sw5e.js, templates/items/weapon.html
handling witch properties to display for different types of weapons
=> Weapon Properties

lang/en.json, less/update/components/actor-global.less, module/actor/entity.js, module/actor/sheets/newSheet/starship.js, module/item/entity.js, module/item/sheet.js, sw5e-global.css, template.json, templates/actors/newActor/parts/swalt-crew.html, templates/actors/newActor/parts/swalt-crewactions.html, templates/items/modification.html
Existing ships and characters will have invalid data, running this as a script macro will fix them:
```javascript
for (const actor of game.actors) {
if (actor.type === "starship") {
await actor.update({"-=data.attributes.deployment": null});
await actor.update({"data.attributes.deployment": {
"pilot": {
"value": null,
"active": false
},
"crew": {
"items": [],
"active": false
},
"passenger": {
"items": [],
"active": false
},
"active": {
"value": null
}
}});
} else if (["character", "npc"].includes(actor.type)) {
await actor.update({"-=data.attributes.deployed": null});
await actor.update({"data.attributes.deployed": {
"uuid": null,
"deployments": []
}});
}
}
```
=> Force starship weapon proficiency, Deployments fix

module/item/sheet.js, sw5e.js
Items can now use modifications directly from the compendium, instead of importing them to world items
=> Compendium Modification Link

lang/en.json, module/applications/item/item-sheet.mjs, module/config.mjs, module/documents/actor/actor.mjs, templates/items/modification.hbs
[Cybernetics and Droid Customization as Modifications](https://github.com/unrealkakeman89/sw5e/commit/e9dd5c299e4ea0d3a339cb17793f29ee419e03c8)
[Hit Dice consume and PrepareData](https://github.com/unrealkakeman89/sw5e/commit/e80ec0424f9cff63cd6a0ec082ab6add2ab75e60)
=> Core upgrade 2.0.2 from beta

lang/en.json, module/applications/actor/trait-selector.mjs, templates/actors/newActor/parts/swalt-features.hbs
Deployment Features Localisation
Damage Resistance Bypass properties
Features Tab CSS
=> Small Fixes

CHANGELOG.MD, lang/en.json, module/applications/actor/base-sheet.mjs, module/applications/actor/starship-sheet.mjs, module/documents/actor/actor.mjs, sw5e.mjs, templates/actors/newActor/parts/swalt-features.hbs, templates/actors/newActor/parts/swalt-inventory.hbs, templates/actors/newActor/starship-sheet.hbs, templates/items/weapon.hbs
Changed starship equipment from 'features' to 'inventory' (can't see why we did that in the first place) Improved weapon reload UI on inventory
=> Starship Equipment, reload ui

CONTRIBUTING.md, README.md, gulpfile.js, package.json
I've ~stolen~ borrowed dnd5e's contributing file and spiced it up for our module. There are some bits I'd like to revise but that would require a long conversation and a possible writing in stone of our current way of doing things, this version will do for now to help people get involved
=> Create contributing file + ensure consistency in build scripts

module/documents/advancement/ability-score-improvement.mjs, static/templates/advancement/ability-score-improvement-flow.hbs
=> Core Update Fixes 3

module/data/item/templates/action.mjs, module/data/item/weapon.mjs, module/documents/item.mjs, static/templates/items/parts/item-action.hbs
Reintroducing Base Critical Threshold, which was lost in the 2.2.2 update
=> Base Critical Threshold
